name: Create Artifact

on:
  workflow_dispatch:
  pull_request:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact
        run: |
          zip -r artifact.zip .
          ls -la
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.zip
